version: "3"

services:
  user-service:
    build: .
    ports:
      - 9090
    restart: always
    networks:
      - grpc-web-demo

networks:
  grpc-web-demo:
    external:
      name: grpc-web-demo